language: ruby
rvm:
 - 2.6.5
before_install:
  - nvm install 11
  - gem install rake
  - bundle install
install:
  - yarn
services:
  - postgresql
before_script:
  - psql -c 'create database launch_delivery_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test
  - RAILS_ENV=test bundle exec rails webpacker:compile